# local-config: referenced, but not emitted by kustomize
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: service-values
  annotations:
    config.kubernetes.io/local-config: "true"
data:
  topologyRef:
    name: default-spread-pods
  preserveJobs: false
  extraMounts:
    - name: v1
      region: r1
      extraVol:
        - propagation:
            - CinderVolume
            - CinderBackup
            - GlanceAPI
            - ManilaShare
          extraVolType: Ceph
          volumes:
            - name: ceph
              projected:
                sources:
                  - secret:
                      name: ceph-conf-files
          mounts:
            - name: ceph
              mountPath: /etc/ceph
              readOnly: true

  glance:
    customServiceConfig: |
      [DEFAULT]
      enabled_backends = default_backend:rbd
      [glance_store]
      default_backend = default_backend
      [default_backend]
      rbd_store_ceph_conf = /etc/ceph/ceph.conf
      store_description = "RBD backend"
      rbd_store_pool = images
      rbd_store_user = openstack
      rbd_thin_provisioning = True
    glanceAPIs:
      azone:
        topologyRef:
          name: azone-node-affinity
        replicas: 2
        type: edge
        storage:
          external: true
      bzone:
        topologyRef:
          name: bzone-node-affinity
        replicas: 2
        type: edge
        storage:
          external: true
      czone:
        topologyRef:
          name: czone-node-affinity
        replicas: 2
        type: edge
        storage:
          external: true
      default:
        replicas: 3
        storage:
          external: true
  cinderAPI:
    replicas: 3
  cinderScheduler:
    replicas: 1
  cinderBackup:
    replicas: 1
    topologyRef:
      name: azone-node-affinity
    customServiceConfig: |
      [DEFAULT]
      backup_driver = cinder.backup.drivers.ceph.CephBackupDriver
      backup_ceph_pool = backups
      backup_ceph_user = openstack
  cinderVolumes:
    ceph:
      topologyRef:
        name: azone-node-affinity
      customServiceConfig: |
        [DEFAULT]
        enabled_backends = ceph
        [ceph]
        volume_backend_name = ceph
        volume_driver = cinder.volume.drivers.rbd.RBDDriver
        rbd_ceph_conf = /etc/ceph/ceph.conf
        rbd_user = openstack
        rbd_pool = volumes
        rbd_flatten_volume_from_snapshot = False
        rbd_secret_uuid = CHANGEME
  manila:
    enabled: true
    manilaAPI:
      replicas: 3
      customServiceConfig: |
        [DEFAULT]
        enabled_share_protocols=cephfs
    manilaScheduler:
      replicas: 3
    manilaShares:
      share1:
        replicas: 1
        topologyRef:
          name: azone-node-affinity
        customServiceConfig: |
          [DEFAULT]
          debug = true
          enabled_share_backends = cephfs
          [cephfs]
          driver_handles_share_servers = False
          share_backend_name = cephfs
          share_driver = manila.share.drivers.cephfs.driver.CephFSDriver
          cephfs_conf_path = /etc/ceph/ceph.conf
          cephfs_cluster_name = ceph
          cephfs_auth_id=openstack
          cephfs_volume_mode = 0755
          cephfs_protocol_helper_type = CEPHFS
  galera:
    templates:
      openstack:
        replicas: 1
        secret: osp-secret
        storageRequest: 5G
      openstack-cell1:
        topologyRef:
          name: azone-node-affinity
        replicas: 1
        secret: osp-secret
        storageRequest: 5G
      openstack-cell2:
        topologyRef:
          name: bzone-node-affinity
        replicas: 1
        secret: osp-secret
        storageRequest: 5G
      openstack-cell3:
        topologyRef:
          name: czone-node-affinity
        replicas: 1
        secret: osp-secret
        storageRequest: 5G
  rabbitmq:
    templates:
      rabbitmq:
        override:
          service:
            metadata:
              annotations:
                metallb.universe.tf/address-pool: internalapi
                metallb.universe.tf/loadBalancerIPs: 172.17.0.85
            spec:
              type: LoadBalancer
        replicas: 3
      rabbitmq-cell1:
        override:
          service:
            metadata:
              annotations:
                metallb.universe.tf/address-pool: internalapi
                metallb.universe.tf/loadBalancerIPs: 172.17.0.86
            spec:
              type: LoadBalancer
        replicas: 3
        topologyRef:
          name: azone-node-affinity
      rabbitmq-cell2:
        override:
          service:
            metadata:
              annotations:
                metallb.universe.tf/address-pool: internalapi
                metallb.universe.tf/loadBalancerIPs: 172.17.0.87
            spec:
              type: LoadBalancer
        replicas: 3
        topologyRef:
          name: bzone-node-affinity
      rabbitmq-cell3:
        override:
          service:
            metadata:
              annotations:
                metallb.universe.tf/address-pool: internalapi
                metallb.universe.tf/loadBalancerIPs: 172.17.0.88
            spec:
              type: LoadBalancer
        replicas: 3
        topologyRef:
          name: czone-node-affinity
  nova:
    customServiceConfig: |
      [DEFAULT]
      default_schedule_zone=az0
    metadataServiceTemplate:
      enabled: false
    cellTemplates:
      cell0:
        cellDatabaseAccount: nova-cell0
        hasAPIAccess: true
      cell1:
        topologyRef:
          name: azone-node-affinity
        cellDatabaseInstance: openstack-cell1
        cellDatabaseAccount: nova-cell1
        cellMessageBusInstance: rabbitmq-cell1
        memcachedInstance: memcached-azone
        conductorServiceTemplate:
          replicas: 1
        hasAPIAccess: true
        metadataServiceTemplate:
          enabled: true
          override:
            service:
              metadata:
                annotations:
                  metallb.universe.tf/address-pool: internalapi
                  metallb.universe.tf/allow-shared-ip: internalapi
                  metallb.universe.tf/loadBalancerIPs: 172.17.0.81
              spec:
                type: LoadBalancer
          replicas: 3
      cell2:
        topologyRef:
          name: bzone-node-affinity
        cellDatabaseInstance: openstack-cell2
        cellDatabaseAccount: nova-cell2
        cellMessageBusInstance: rabbitmq-cell2
        memcachedInstance: memcached-bzone
        conductorServiceTemplate:
          replicas: 1
        hasAPIAccess: true
        metadataServiceTemplate:
          enabled: true
          override:
            service:
              metadata:
                annotations:
                  metallb.universe.tf/address-pool: internalapi
                  metallb.universe.tf/allow-shared-ip: internalapi
                  metallb.universe.tf/loadBalancerIPs: 172.17.0.82
              spec:
                type: LoadBalancer
          replicas: 3
      cell3:
        topologyRef:
          name: czone-node-affinity
        cellDatabaseInstance: openstack-cell3
        cellDatabaseAccount: nova-cell3
        cellMessageBusInstance: rabbitmq-cell3
        memcachedInstance: memcached-czone
        conductorServiceTemplate:
          replicas: 1
        hasAPIAccess: true
        metadataServiceTemplate:
          enabled: true
          override:
            service:
              metadata:
                annotations:
                  metallb.universe.tf/address-pool: internalapi
                  metallb.universe.tf/allow-shared-ip: internalapi
                  metallb.universe.tf/loadBalancerIPs: 172.17.0.83
              spec:
                type: LoadBalancer
          replicas: 3
  memcached:
    templates:
      memcached:
        replicas: 3
      memcached-azone:
        replicas: 3
        topologyRef:
          name: azone-node-affinity
      memcached-bzone:
        replicas: 3
        topologyRef:
          name: bzone-node-affinity
      memcached-czone:
        replicas: 3
        topologyRef:
          name: czone-node-affinity
