---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
  - ../../../../va/hci/

resources:
  - networking/nncp/values.yaml
  - service-values.yaml

replacements:
  # add external storage true for testing without RWX PVCs
  - source:
      kind: ConfigMap
      name: service-values
      fieldPath: data.glance.glanceAPIs.default.storage
    targets:
      - select:
          kind: OpenStackControlPlane
        fieldPaths:
          - spec.glance.template.glanceAPIs.default.storage
        options:
          create: true

  # add topologyRef.name to spread all pods across zones
  - source:
      kind: ConfigMap
      name: service-values
      fieldPath: data.topologyRef.name
    targets:
      - select:
          kind: OpenStackControlPlane
        fieldPaths:
          - spec.topologyRef.name
        options:
          create: true

  # cells from service-values.yaml
  - source:
      kind: ConfigMap
      name: service-values
      fieldPath: data.nova.metadataServiceTemplate
    targets:
      - select:
          kind: OpenStackControlPlane
        fieldPaths:
          - spec.nova.template.metadataServiceTemplate
        options:
          create: true
  - source:
      kind: ConfigMap
      name: service-values
      fieldPath: data.nova.cellTemplates
    targets:
      - select:
          kind: OpenStackControlPlane
        fieldPaths:
          - spec.nova.template.cellTemplates
        options:
          create: true
  - source:
      kind: ConfigMap
      name: service-values
      fieldPath: data.galera.templates
    targets:
      - select:
          kind: OpenStackControlPlane
        fieldPaths:
          - spec.galera.templates
        options:
          create: true
  - source:
      kind: ConfigMap
      name: service-values
      fieldPath: data.rabbitmq.templates
    targets:
      - select:
          kind: OpenStackControlPlane
        fieldPaths:
          - spec.rabbitmq.templates
        options:
          create: true

  # memcached
  - source:
      kind: ConfigMap
      name: service-values
      fieldPath: data.memcached.templates
    targets:
      - select:
          kind: OpenStackControlPlane
        fieldPaths:
          - spec.memcached.templates
        options:
          create: true
