---
apiVersion: v1
kind: ConfigMap
metadata:
  name: service-values
  annotations:
    config.kubernetes.io/local-config: "true"
data:
  topologyRef:
    name: default-spread-pods
  preserveJobs: false
  glance:
    glanceAPIs:
      default:
        storage:
          external: true
  galera:
    templates:
      openstack:
        replicas: 3
        secret: osp-secret
        storageRequest: 5G
      openstack-cell1:
        replicas: 3
        secret: osp-secret
        storageRequest: 5G
      openstack-cell2:
        replicas: 3
        secret: osp-secret
        storageRequest: 5G
      openstack-cell3:
        replicas: 3
        secret: osp-secret
        storageRequest: 5G
  rabbitmq:
    templates:
      rabbitmq:
        override:
          service:
            metadata:
              annotations:
                metallb.universe.tf/address-pool: internalapi
                metallb.universe.tf/loadBalancerIPs: 172.17.0.85
            spec:
              type: LoadBalancer
        replicas: 3
      rabbitmq-cell1:
        override:
          service:
            metadata:
              annotations:
                metallb.universe.tf/address-pool: internalapi
                metallb.universe.tf/loadBalancerIPs: 172.17.0.86
            spec:
              type: LoadBalancer
        replicas: 3
        topologyRef:
          name: azone-node-affinity
      rabbitmq-cell2:
        override:
          service:
            metadata:
              annotations:
                metallb.universe.tf/address-pool: internalapi
                metallb.universe.tf/loadBalancerIPs: 172.17.0.87
            spec:
              type: LoadBalancer
        replicas: 3
        topologyRef:
          name: bzone-node-affinity
      rabbitmq-cell3:
        override:
          service:
            metadata:
              annotations:
                metallb.universe.tf/address-pool: internalapi
                metallb.universe.tf/loadBalancerIPs: 172.17.0.88
            spec:
              type: LoadBalancer
        replicas: 3
        topologyRef:
          name: czone-node-affinity
  nova:
    customServiceConfig: |
      [DEFAULT]
      default_schedule_zone=az0
    metadataServiceTemplate:
      enabled: false
    cellTemplates:
      cell0:
        cellDatabaseAccount: nova-cell0
        hasAPIAccess: true
      cell1:
        topologyRef:
          name: azone-node-affinity
        cellDatabaseInstance: openstack-cell1
        cellDatabaseAccount: nova-cell1
        cellMessageBusInstance: rabbitmq-cell1
        memcachedInstance: memcached-azone
        conductorServiceTemplate:
          replicas: 1
        hasAPIAccess: true
        metadataServiceTemplate:
          enabled: true
          replicas: 3
      cell2:
        topologyRef:
          name: bzone-node-affinity
        cellDatabaseInstance: openstack-cell2
        cellDatabaseAccount: nova-cell2
        cellMessageBusInstance: rabbitmq-cell2
        memcachedInstance: memcached-bzone
        conductorServiceTemplate:
          replicas: 1
        hasAPIAccess: true
        metadataServiceTemplate:
          enabled: true
          replicas: 3
      cell3:
        topologyRef:
          name: czone-node-affinity
        cellDatabaseInstance: openstack-cell3
        cellDatabaseAccount: nova-cell3
        cellMessageBusInstance: rabbitmq-cell3
        memcachedInstance: memcached-czone
        conductorServiceTemplate:
          replicas: 1
        hasAPIAccess: true
        metadataServiceTemplate:
          enabled: true
          replicas: 3
  memcached:
    templates:
      memcached:
        replicas: 3
      memcached-azone:
        replicas: 3
        topologyRef:
          name: azone-node-affinity
      memcached-bzone:
        replicas: 3
        topologyRef:
          name: bzone-node-affinity
      memcached-czone:
        replicas: 3
        topologyRef:
          name: czone-node-affinity
