---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
  - ../../../../../../../dt/bgp/edpm/deployment

resources:
  - values.yaml

patches:
- patch: |
    - op: replace
      path: /metadata/name
      value: edpm-post-ceph-computes-deployment-r0
  target:
    kind: OpenStackDataPlaneDeployment
    name: edpm-deployment

replacements:
  - source:
      kind: ConfigMap
      name: edpm-deployment-values
      fieldPath: data.nodeSets
    targets:
      - select:
          kind: OpenStackDataPlaneDeployment
        fieldPaths:
          - spec.nodeSets
  - source:
      kind: ConfigMap
      name: edpm-deployment-values
      fieldPath: data.services
    targets:
      - select:
          kind: OpenStackDataPlaneDeployment
        fieldPaths:
          - spec.servicesOverride
        options:
          create: true
