# local-config: referenced, but not emitted by kustomize
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: edpm-deployment-values
  annotations:
    config.kubernetes.io/local-config: "true"
data:
  deployment:
    name: edpm-deployment-post-ceph-networkers
  nodeSets:
    - r0-networker-nodes
    - r1-networker-nodes
    - r2-networker-nodes
  services:
    - neutron-metadata
    - ovn-bgp-agent
