---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
  - ../../../../../../dt/bgp/edpm/nodeset
  ## It's possible to replace ../../../../../../dt/bgp/edpm/nodeset with a git checkout URL as per:
  ## https://github.com/kubernetes-sigs/kustomize/blob/master/examples/remoteBuild.md

resources:
  - values.yaml

patches:
  - target:
      kind: OpenStackDataPlaneNodeSet
      name: .*
    patch: |-
      - op: replace
        path: /metadata/name
        value: r0-compute-nodes

replacements:
  # Add ceph extra mounts to HCI compute nodes
  - source:
      kind: ConfigMap
      name: edpm-nodeset-values
      fieldPath: data.nodeTemplate.extraMounts
    targets:
      - select:
          kind: OpenStackDataPlaneNodeSet
        fieldPaths:
          - spec.nodeTemplate.extraMounts
        options:
          create: true
