- ip: 192.168.111.10
  hostnames:
    - "master-0"
- ip: 192.168.111.11
  hostnames:
    - "master-1"
- ip: 192.168.111.12
  hostnames:
    - "master-2"
- ip: 192.168.111.13
  hostnames:
    - "worker-0"
- ip: 192.168.111.14
  hostnames:
    - "worker-1"
- ip: 192.168.111.15
  hostnames:
    - "worker-2"
- ip: 192.168.111.16
  hostnames:
    - "worker-3"
- ip: 192.168.111.17
  hostnames:
    - "worker-4"
- ip: 192.168.111.18
  hostnames:
    - "worker-5"
- ip: 192.168.111.19
  hostnames:
    - "worker-6"
- ip: 192.168.111.20
  hostnames:
    - "worker-7"
- ip: 192.168.111.21
  hostnames:
    - "worker-8"
- ip: 192.168.111.22
  hostnames:
    - "worker-9"

