# REMOVE_ME
# Provided as a better alternative to this:
#   https://github.com/fultonj/architecture/tree/ci-framework
# But should be genereated by ci-framework in the future

# Replace all `enp6s0` below with output of this command:
#   oc debug node/master-0 -- chroot /host nmcli \
#      -g GENERAL.DEVICE,IP4.ADDRESS device show | \
#      grep -B 1 168.122 | head -1

apiVersion: v1
kind: ConfigMap
metadata:
  name: network-values
  annotations:
    config.kubernetes.io/local-config: "true"
data:
  node_0:
    name: master-0
    internalapi_ip: 172.17.0.5
    tenant_ip: 172.19.0.5
    ctlplane_ip: 192.168.122.10
    storage_ip: 172.18.0.5
  node_1:
    name: master-1
    internalapi_ip: 172.17.0.6
    tenant_ip: 172.19.0.6
    ctlplane_ip: 192.168.122.11
    storage_ip: 172.18.0.6
  node_2:
    name: master-2
    internalapi_ip: 172.17.0.7
    tenant_ip: 172.19.0.7
    ctlplane_ip: 192.168.122.12
    storage_ip: 172.18.0.7

  dns-resolver:
    config:
      server:
        - 192.168.122.1
        - 10.47.242.10
        - 10.38.5.26
  routes:
    config:
    - destination: 0.0.0.0/0
      next-hop-address: 192.168.122.1
      next-hop-interface: enp6s0

  ctlplane:
    iface: enp6s0
    mtu: 1500
    lb_addresses:
    - 192.168.122.80-192.168.122.90
    endpoint_annotations:
      metallb.universe.tf/address-pool: ctlplane
      metallb.universe.tf/allow-shared-ip: ctlplane
      metallb.universe.tf/loadBalancerIPs: 192.168.122.80
  internalapi:
    iface: enp6s0.20
    vlan: 20
    base_iface: enp6s0
    lb_addresses:
    - 172.17.0.80-172.17.0.90
    endpoint_annotations:
      metallb.universe.tf/address-pool: internalapi
      metallb.universe.tf/allow-shared-ip: internalapi
      metallb.universe.tf/loadBalancerIPs: 172.17.0.80
  storage:
    iface: enp6s0.21
    vlan: 21
    base_iface: enp6s0
    lb_addresses:
    - 172.18.0.80-172.18.0.90
  tenant:
    iface: enp6s0.22
    vlan: 22
    base_iface: enp6s0
    lb_addresses:
    - 172.19.0.80-172.19.0.90

  rabbitmq:
    endpoint_annotations:
      metallb.universe.tf/address-pool: internalapi
      metallb.universe.tf/loadBalancerIPs: 172.17.0.85
  rabbitmq-cell1:
    endpoint_annotations:
      metallb.universe.tf/address-pool: internalapi
      metallb.universe.tf/loadBalancerIPs: 172.17.0.86

  lbServiceType: LoadBalancer
