apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - nova_ceph.yaml
  - values.yaml

replacements:
  - source:
      kind: ConfigMap
      name: edpm-deployment-values
      fieldPath: data.nova.ceph.conf
    targets:
      - select:
          kind: ConfigMap
          name: ceph-nova-az2
        fieldPaths:
          - data.03-ceph-nova\.conf
        options:
          create: true
