apiVersion: v1
kind: Secret
metadata:
  labels:
    component: cinder-volume
    service: cinder
  name: cinder-volume-ontap-secrets-az2
  namespace: openstack
stringData:
  cinder-volume-ontap-secrets-az2: |
    [ontap]
    netapp_login = <login>
    netapp_password = <password>
    netapp_vserver = <vserver>
    netapp_pool_name_search_pattern = (my_pool) 