---
apiVersion: v1
kind: Secret
metadata:
  labels:
    service: cinder
    component: cinder-volume
  name: cinder-volume-secrets-az1
type: Opaque
stringData:
  cinder-volume-secrets-az1: _replaced_
