apiVersion: v1
kind: Secret
metadata:
  name: osp-secret-manila-az1
  namespace: openstack
stringData:
  netapp-secrets.conf: |
    [nfs_az1]
    netapp_server_hostname = 10.2.0.6
    netapp_login = <redacted>
    netapp_password = <redacted>
    netapp_vserver = vserver-rhos-1 