kind: ConfigMap
apiVersion: v1
metadata:
    name: service-values
    annotations:
        config.kubernetes.io/local-config: 'true'
data:
  topologyRef:
    name: default-spread-pods
  preserveJobs: false
  neutron:
    customServiceConfig: '[DEFAULT]

        vlan_transparent = true

        debug = true

        [ovs]

        igmp_snooping_enable = true

        '
  octavia:
    amphoraImageContainerImage: quay.io/gthiemonge/octavia-amphora-image
    apacheContainerImage: registry.redhat.io/ubi9/httpd-24:latest
    enabled: false
    octaviaAPI:
      customServiceConfig: '[controller_worker]

          loadbalancer_topology=ACTIVE_STANDBY

          '
      networkAttachments:
      - internalapi
    octaviaHealthManager:
      customServiceConfig: '[controller_worker]

          loadbalancer_topology=ACTIVE_STANDBY

          '
      networkAttachments:
      - octavia
    octaviaHousekeeping:
      customServiceConfig: '[controller_worker]

          loadbalancer_topology=ACTIVE_STANDBY

          '
      networkAttachments:
      - octavia
    octaviaWorker:
      customServiceConfig: '[controller_worker]

          loadbalancer_topology=ACTIVE_STANDBY

          '
      networkAttachments:
      - octavia
  ovn:
    ovnController:
      external-ids:
        enable-chassis-as-gateway: false

  preserveJobs: false
  swift:
    enabled: false

  memcached:
    templates:
      memcached:
        replicas: 3
      memcached-azone:
        replicas: 3
        topologyRef:
          name: azone-node-affinity
      memcached-bzone:
        replicas: 3
        topologyRef:
          name: bzone-node-affinity
      memcached-czone:
        replicas: 3
        topologyRef:
          name: czone-node-affinity

  glance:
    # This glance.customServiceConfig is only here
    # to pacify ../../../../dt/bgp/ and is ignored
    # since a separate customServiceConfig is in
    # place for each glance
    customServiceConfig: ""
    # This glance.default.replicas is here
    # to pacify ../../../../dt/bgp/
    # replicas are set separately for each glance later
    # For the pre-ceph control-plane this is set to 0
    # since we do not have yet have a storage backend
    default:
      replicas: 0

  nova:
    customServiceConfig: |
      [DEFAULT]
      default_schedule_zone=az0
    metadataServiceTemplate:
      enabled: true
      # if cells per zone, set false
      # enabled: false
    cellTemplates:
      cell0:
        cellDatabaseAccount: nova-cell0
        hasAPIAccess: true
      # if cells per zone, uncomment topologyRef
      cell1:
        # topologyRef:
        #   name: azone-node-affinity
        cellDatabaseInstance: openstack-cell1
        cellDatabaseAccount: nova-cell1
        cellMessageBusInstance: rabbitmq-cell1
        conductorServiceTemplate:
          replicas: 1
        hasAPIAccess: true
        # if cells per zone, uncomment to deploy metadataService per zone
        # metadataServiceTemplate:
        #   enabled: true
        #   replicas: 3
      # if cells per zone, uncomment cell2 and cell3
      # cell2:
      #   topologyRef:
      #     name: bzone-node-affinity
      #   cellDatabaseInstance: openstack-cell2
      #   cellDatabaseAccount: nova-cell2
      #   cellMessageBusInstance: rabbitmq-cell2
      #   conductorServiceTemplate:
      #     replicas: 1
      #   hasAPIAccess: true
      #   metadataServiceTemplate:
      #     enabled: true
      #     replicas: 3
      # cell3:
      #   topologyRef:
      #     name: czone-node-affinity
      #   cellDatabaseInstance: openstack-cell3
      #   cellDatabaseAccount: nova-cell3
      #   cellMessageBusInstance: rabbitmq-cell3
      #   conductorServiceTemplate:
      #     replicas: 1
      #   hasAPIAccess: true
      #   metadataServiceTemplate:
      #     enabled: true
      #     replicas: 3
  rabbitmq:
    templates:
      rabbitmq:
        override:
          service:
            metadata:
              annotations:
                metallb.universe.tf/address-pool: internalapi
                metallb.universe.tf/loadBalancerIPs: 172.17.0.85
            spec:
              type: LoadBalancer
        replicas: 3
      rabbitmq-cell1:
        override:
          service:
            metadata:
              annotations:
                metallb.universe.tf/address-pool: internalapi
                metallb.universe.tf/loadBalancerIPs: 172.17.0.86
            spec:
              type: LoadBalancer
        replicas: 3
        # if cells per zone, uncomment topologyRef
        # topologyRef:
        #   name: azone-node-affinity
      # if cells per zone, uncomment cell2 and cell2
      # rabbitmq-cell2:
      #   override:
      #     service:
      #       metadata:
      #         annotations:
      #           metallb.universe.tf/address-pool: internalapi
      #           metallb.universe.tf/loadBalancerIPs: 172.17.0.87
      #       spec:
      #         type: LoadBalancer
      #   replicas: 3
      #   topologyRef:
      #     name: bzone-node-affinity
      # rabbitmq-cell3:
      #   override:
      #     service:
      #       metadata:
      #         annotations:
      #           metallb.universe.tf/address-pool: internalapi
      #           metallb.universe.tf/loadBalancerIPs: 172.17.0.88
      #       spec:
      #         type: LoadBalancer
      #   replicas: 3
      #   topologyRef:
      #     name: czone-node-affinity
  galera:
    templates:
      openstack:
        replicas: 3
        secret: osp-secret
        storageRequest: 5G
      openstack-cell1:
        replicas: 3
        secret: osp-secret
        storageRequest: 5G
      # if cells per zone, uncomment cell1 and cell3
      # openstack-cell2:
      #   replicas: 3
      #   secret: osp-secret
      #   storageRequest: 5G
      # openstack-cell3:
      #   replicas: 3
      #   secret: osp-secret
      #   storageRequest: 5G
