# local-config: referenced, but not emitted by kustomize
apiVersion: v1
kind: ConfigMap
metadata:
  name: nncp-values
  annotations:
    config.kubernetes.io/local-config: "true"
data:
  # nodes
  node_0:
    name: ostest-master-0
    internalapi_ip: 172.17.0.5
    tenant_ip: 172.19.0.5
    ctlplane_ip: 192.168.122.10
    storage_ip: 172.18.0.5
  node_1:
    name: ostest-master-1
    internalapi_ip: 172.17.0.6
    tenant_ip: 172.19.0.6
    ctlplane_ip: 192.168.122.11
    storage_ip: 172.18.0.6
  node_2:
    name: ostest-master-2
    internalapi_ip: 172.17.0.7
    tenant_ip: 172.19.0.7
    ctlplane_ip: 192.168.122.12
    storage_ip: 172.18.0.7

  # networks
  ctlplane:
    mtu: 9000
    prefix-length: 24
    base_iface: enp7s0
  internalapi:
    mtu: 1500
    prefix-length: 24
    vlan: 20
    base_iface: enp7s0
  storage:
    mtu: 9000
    prefix-length: 24
    vlan: 21
    base_iface: enp7s0
  storagemgmt:  # used on RHEL, not used on OpenShift
    mtu: 9000
  tenant:
    mtu: 1500
    prefix-length: 24
    vlan: 22
    base_iface: enp7s0
  external:
    mtu: 1500

  dns-resolver:
    config:
      server:
        - 192.168.122.1
      search: []
    options:
      - key: server
        values:
          - 192.168.122.1

  routes:
    config:
    - destination: 0.0.0.0/0
      next-hop-address: 192.168.122.1
      next-hop-interface: enp7s0
