---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# fix me:
# update control plane to use ceph and create compute deployment (from old previous step)

components:
  - ../../../dt/bgp/

resources:
  - service-values.yaml
  - control-plane/nncp/values.yaml
  - control-plane/metallb_bgppeers.yaml
  - control-plane/ocp_networks_netattach.yaml

transformers:
  # Set namespace to OpenStack on all namespaced objects without a namespace
  - |-
    apiVersion: builtin
    kind: NamespaceTransformer
    metadata:
      name: _ignored_
      namespace: openstack
    setRoleBindingSubjects: none
    unsetOnly: true
    fieldSpecs:
      - path: metadata/name
        kind: Namespace
        create: true

patches:
  # Add BGPPeer to BGPAdvertisement
  - target:
      kind: BGPAdvertisement
    patch: |-
      - op: add
        path: /spec/peers/-
        value: bgp-peer-node-3-0
      - op: add
        path: /spec/peers/-
        value: bgp-peer-node-3-1
      - op: add
        path: /spec/peers/-
        value: bgp-peer-node-4-0
      - op: add
        path: /spec/peers/-
        value: bgp-peer-node-4-1
      - op: add
        path: /spec/peers/-
        value: bgp-peer-node-5-0
      - op: add
        path: /spec/peers/-
        value: bgp-peer-node-5-1
      - op: add
        path: /spec/peers/-
        value: bgp-peer-node-6-0
      - op: add
        path: /spec/peers/-
        value: bgp-peer-node-6-1
      - op: add
        path: /spec/peers/-
        value: bgp-peer-node-7-0
      - op: add
        path: /spec/peers/-
        value: bgp-peer-node-7-1
      - op: add
        path: /spec/peers/-
        value: bgp-peer-node-8-0
      - op: add
        path: /spec/peers/-
        value: bgp-peer-node-8-1
      - op: add
        path: /spec/peers/-
        value: bgp-peer-node-9-0
      - op: add
        path: /spec/peers/-
        value: bgp-peer-node-9-1
      - op: add
        path: /spec/peers/-
        value: bgp-peer-node-10-0
      - op: add
        path: /spec/peers/-
        value: bgp-peer-node-10-1
      - op: add
        path: /spec/peers/-
        value: bgp-peer-node-11-0
      - op: add
        path: /spec/peers/-
        value: bgp-peer-node-11-1
      - op: add
        path: /spec/peers/-
        value: bgp-peer-node-12-0
  - target:
      kind: NetworkAttachmentDefinition
      labelSelector: "osp/net-attach-def-type=bgp"
    path: control-plane/ocp_network_template.yaml

  # All L2Advertisements are removed
  - target:
      kind: L2Advertisement
    patch: |-
      kind: L2Advertisement
      metadata:
        name: .*
      $patch: delete

replacements:
  # BGP peer IP addresses
  # node3
  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.node_3.bgp_peers.0
    targets:
      - select:
          kind: BGPPeer
          name: bgp-peer-node-3-0
        fieldPaths:
          - spec.peerAddress
  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.node_3.bgp_peers.1
    targets:
      - select:
          kind: BGPPeer
          name: bgp-peer-node-3-1
        fieldPaths:
          - spec.peerAddress
  # node4
  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.node_4.bgp_peers.0
    targets:
      - select:
          kind: BGPPeer
          name: bgp-peer-node-4-0
        fieldPaths:
          - spec.peerAddress
  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.node_4.bgp_peers.1
    targets:
      - select:
          kind: BGPPeer
          name: bgp-peer-node-4-1
        fieldPaths:
          - spec.peerAddress
  # node5
  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.node_5.bgp_peers.0
    targets:
      - select:
          kind: BGPPeer
          name: bgp-peer-node-5-0
        fieldPaths:
          - spec.peerAddress
  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.node_5.bgp_peers.1
    targets:
      - select:
          kind: BGPPeer
          name: bgp-peer-node-5-1
        fieldPaths:
          - spec.peerAddress
  # node6
  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.node_6.bgp_peers.0
    targets:
      - select:
          kind: BGPPeer
          name: bgp-peer-node-6-0
        fieldPaths:
          - spec.peerAddress
  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.node_6.bgp_peers.1
    targets:
      - select:
          kind: BGPPeer
          name: bgp-peer-node-6-1
        fieldPaths:
          - spec.peerAddress
  # node7
  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.node_7.bgp_peers.0
    targets:
      - select:
          kind: BGPPeer
          name: bgp-peer-node-7-0
        fieldPaths:
          - spec.peerAddress
  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.node_7.bgp_peers.1
    targets:
      - select:
          kind: BGPPeer
          name: bgp-peer-node-7-1
        fieldPaths:
          - spec.peerAddress
  # node8
  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.node_8.bgp_peers.0
    targets:
      - select:
          kind: BGPPeer
          name: bgp-peer-node-8-0
        fieldPaths:
          - spec.peerAddress
  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.node_8.bgp_peers.1
    targets:
      - select:
          kind: BGPPeer
          name: bgp-peer-node-8-1
        fieldPaths:
          - spec.peerAddress
  # node9
  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.node_9.bgp_peers.0
    targets:
      - select:
          kind: BGPPeer
          name: bgp-peer-node-9-0
        fieldPaths:
          - spec.peerAddress
  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.node_9.bgp_peers.1
    targets:
      - select:
          kind: BGPPeer
          name: bgp-peer-node-9-1
        fieldPaths:
          - spec.peerAddress
  # node10
  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.node_10.bgp_peers.0
    targets:
      - select:
          kind: BGPPeer
          name: bgp-peer-node-10-0
        fieldPaths:
          - spec.peerAddress
  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.node_10.bgp_peers.1
    targets:
      - select:
          kind: BGPPeer
          name: bgp-peer-node-10-1
        fieldPaths:
          - spec.peerAddress
  # node11
  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.node_11.bgp_peers.0
    targets:
      - select:
          kind: BGPPeer
          name: bgp-peer-node-11-0
        fieldPaths:
          - spec.peerAddress
  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.node_11.bgp_peers.1
    targets:
      - select:
          kind: BGPPeer
          name: bgp-peer-node-11-1
        fieldPaths:
          - spec.peerAddress
  # node12
  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.node_12.bgp_peers.0
    targets:
      - select:
          kind: BGPPeer
          name: bgp-peer-node-12-0
        fieldPaths:
          - spec.peerAddress

  # BGP NetworkAttachmentDefinition customization
  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.bgp.net-attach-def.node12
    targets:
      - select:
          kind: NetworkAttachmentDefinition
          name: bgpnet-worker-9
        fieldPaths:
          - spec.config

  # disable OCP workers as gateway nodes
  - source:
      kind: ConfigMap
      name: service-values
      fieldPath: data.ovn.ovnController.external-ids
    targets:
      - select:
          kind: OpenStackControlPlane
        fieldPaths:
          - spec.ovn.template.ovnController.external-ids
        options:
          create: true

  # configure neutron customServiceConfig
  - source:
      kind: ConfigMap
      name: service-values
      fieldPath: data.neutron.customServiceConfig
    targets:
      - select:
          kind: OpenStackControlPlane
        fieldPaths:
          - spec.neutron.template.customServiceConfig
        options:
          create: true

  # add topologyRef.name to spread all pods across zones
  - source:
      kind: ConfigMap
      name: service-values
      fieldPath: data.topologyRef.name
    targets:
      - select:
          kind: OpenStackControlPlane
        fieldPaths:
          - spec.topologyRef.name
        options:
          create: true

  # topologyRef.name will be added to cinderVolumes under each volume.
  # For example everything under `ceph` is injected already and the
  # service-values.yaml already has a topologyRef.

  - source:
      kind: ConfigMap
      name: service-values
      fieldPath: data.cinderVolumes
    targets:
      - select:
          kind: OpenStackControlPlane
        fieldPaths:
          - spec.cinder.template.cinderVolumes
        options:
          create: true
  - source:
      kind: ConfigMap
      name: service-values
      fieldPath: data.cinderAPI.replicas
    targets:
      - select:
          kind: OpenStackControlPlane
        fieldPaths:
          - spec.cinder.template.cinderAPI.replicas
        options:
          create: true
  - source:
      kind: ConfigMap
      name: service-values
      fieldPath: data.cinder.customServiceConfig
    targets:
      - select:
          kind: OpenStackControlPlane
        fieldPaths:
          - spec.cinder.template.customServiceConfig
        options:
          create: true
  - source:
      kind: ConfigMap
      name: service-values
      fieldPath: data.cinderBackup.replicas
    targets:
      - select:
          kind: OpenStackControlPlane
        fieldPaths:
          - spec.cinder.template.cinderBackup.replicas
        options:
          create: true
  - source:
      kind: ConfigMap
      name: service-values
      fieldPath: data.cinderBackup.customServiceConfig
    targets:
      - select:
          kind: OpenStackControlPlane
        fieldPaths:
          - spec.cinder.template.cinderBackup.customServiceConfig
        options:
          create: true

  # Set topologyRef.name for cinderBackup
  - source:
      kind: ConfigMap
      name: service-values
      fieldPath: data.cinderBackup.topologyRef.name
    targets:
      - select:
          kind: OpenStackControlPlane
        fieldPaths:
          - spec.cinder.template.cinderBackup.topologyRef.name
        options:
          create: true
  # manila
  - source:
      kind: ConfigMap
      name: service-values
      fieldPath: data.manila.enabled
    targets:
      - select:
          kind: OpenStackControlPlane
        fieldPaths:
          - spec.manila.enabled
        options:
          create: true
  - source:
      kind: ConfigMap
      name: service-values
      fieldPath: data.manila.manilaAPI.customServiceConfig
    targets:
      - select:
          kind: OpenStackControlPlane
        fieldPaths:
          - spec.manila.template.manilaAPI.customServiceConfig
        options:
          create: true
  - source:
      kind: ConfigMap
      name: service-values
      fieldPath: data.manila.manilaShares
    targets:
      - select:
          kind: OpenStackControlPlane
        fieldPaths:
          - spec.manila.template.manilaShares
        options:
          create: true
  # set manila api replcias to 3 (unlike in cinder)
  - source:
      kind: ConfigMap
      name: service-values
      fieldPath: data.manila.manilaAPI.replicas
    targets:
      - select:
          kind: OpenStackControlPlane
        fieldPaths:
          - spec.manila.template.manilaAPI.replicas
        options:
          create: true
  # set manila scheduler replcias to 3 (unlike in cinder)
  - source:
      kind: ConfigMap
      name: service-values
      fieldPath: data.manila.manilaScheduler.replicas
    targets:
      - select:
          kind: OpenStackControlPlane
        fieldPaths:
          - spec.manila.template.manilaScheduler.replicas
        options:
          create: true

  # GLANCE
  # optional: external storage true for testing failover with LVMS
  # - source:
  #     kind: ConfigMap
  #     name: service-values
  #     fieldPath: data.glance.glanceAPIs.default.storage
  #   targets:
  #     - select:
  #         kind: OpenStackControlPlane
  #       fieldPaths:
  #         - spec.glance.template.glanceAPIs.default.storage
  #       options:
  #         create: true

  # Set glance template keystoneEndpoint
  - source:
      kind: ConfigMap
      name: service-values
      fieldPath: data.glance.keystoneEndpoint
    targets:
      - select:
          kind: OpenStackControlPlane
        fieldPaths:
          - spec.glance.template.keystoneEndpoint
        options:
          create: true

  # Set all four glanceAPIs (default, az{0,1,2})
  - source:
      kind: ConfigMap
      name: service-values
      fieldPath: data.glance.glanceAPIs
    targets:
      - select:
          kind: OpenStackControlPlane
        fieldPaths:
          - spec.glance.template.glanceAPIs
        options:
          create: true

  # memcached
  - source:
      kind: ConfigMap
      name: service-values
      fieldPath: data.memcached.templates
    targets:
      - select:
          kind: OpenStackControlPlane
        fieldPaths:
          - spec.memcached.templates
        options:
          create: true

  # Nova cells
  - source:
      kind: ConfigMap
      name: service-values
      fieldPath: data.nova.metadataServiceTemplate
    targets:
      - select:
          kind: OpenStackControlPlane
        fieldPaths:
          - spec.nova.template.metadataServiceTemplate
        options:
          create: true
  - source:
      kind: ConfigMap
      name: service-values
      fieldPath: data.nova.cellTemplates
    targets:
      - select:
          kind: OpenStackControlPlane
        fieldPaths:
          - spec.nova.template.cellTemplates
        options:
          create: true
  - source:
      kind: ConfigMap
      name: service-values
      fieldPath: data.galera.templates
    targets:
      - select:
          kind: OpenStackControlPlane
        fieldPaths:
          - spec.galera.templates
        options:
          create: true
  - source:
      kind: ConfigMap
      name: service-values
      fieldPath: data.rabbitmq.templates
    targets:
      - select:
          kind: OpenStackControlPlane
        fieldPaths:
          - spec.rabbitmq.templates
        options:
          create: true

  # ceph secret extra mounts
  - source:
      kind: ConfigMap
      name: service-values
      fieldPath: data.extraMounts
    targets:
      - select:
          kind: OpenStackControlPlane
        fieldPaths:
          - spec.extraMounts
        options:
          create: true
